version: "3.9"

services:
  database:
    container_name: eve_database
    restart: unless-stopped
    build:
      context: ./database
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - network
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 2s
      timeout: 1s
      retries: 10
  migrate:
    container_name: eve_migrate
    restart: unless-stopped
    build:
      context: ./migrate
    volumes:
      - ./migrate:/migrate
      - /migrate/node_modules
    env_file:
      - ./.env
    networks:
      - network
    depends_on:
      database:
        condition: service_healthy
    command: ["--", "watch"]
  worker:
    container_name: eve_worker
    restart: unless-stopped
    build:
      context: ./worker
    volumes:
      - ./worker:/worker
      - /worker/node_modules
    env_file:
      - ./.env
    networks:
      - network
    depends_on:
      database:
        condition: service_healthy
    command: ["--", "--watch"]
  graphql:
    container_name: eve_graphql
    restart: unless-stopped
    build:
      context: ./graphql
    env_file:
      - ./.env
    networks:
      - network
    ports:
      - 5433:5433
    depends_on:
      database:
        condition: service_healthy
    command:
      [
        "--",
        "--connection", "${DATABASE_URL}",
        "--owner-connection", "${SUPERUSER_APPLICATION_DATABASE_URL}",
        "--port", "5433",
        "--schema", "public",
        "--subscriptions",
        "--watch",
        "--dynamic-json",
        "--no-setof-functions-contain-nulls",
        "--no-ignore-rbac",
        "--show-error-stack=json",
        "--extended-errors", "hint,detail,errcode",
        "--export-schema-graphql", "schema.graphql",
        "--graphiql", "/",
        "--enhance-graphiql",
        "--allow-explain",
        "--enable-query-batching",
        "--legacy-relations", "omit",
        "--append-plugins", "@graphile-contrib/pg-order-by-related,@graphile-contrib/pg-simplify-inflector,postgraphile-plugin-connection-filter,postgraphile-plugin-nested-mutations"
      ]
  client:
    container_name: eve_client
    restart: unless-stopped
    build:
      context: ./client
      args:
        - GRAPHQL_URL
    volumes:
      - ./client:/client
      - /client/node_modules
      - /client/.next
    env_file:
      - ./.env
    networks:
      - network
    ports:
      - 3000:3000
    command: ["npm", "run", "dev"]

networks:
  network:

volumes:
  database:
